### ISSUE TITLE
unable to sudo

### ISSUE THREAD

**Issue by chazragg** [geerlingguy/ansible-role-github-users#3]
Hello, I am a bit new to all of this so sorry if it is an easy answer.

when using this role to create accounts I am unable to use sudo on them accounts. I am asked for a password but for what I can see there is none where set. is there a default password? i tried using blank but that didn't do anything.

if I manually go onto the machine and set a password for the user all works well.

**Comment by geerlingguy** [comment]
This role doesn't set any passwords for the users it creates (see task here: https://github.com/geerlingguy/ansible-role-github-users/blob/master/tasks/main.yml#L4-L9).

If you want to allow accounts to use `sudo` you can also configure that separately via the `sudoers` file using Ansible's `template` module or `lineinfile` to modify it.

For now I don't want to add any kind of password management for user account to this role as that can get pretty complicated.

**Comment by chazragg** [comment]
Perfect, thank you for the help!
